### ISSUE TITLE
Compilation error with lammps

### ISSUE THREAD

**Issue by ajhaver4** [adavtyan/awsemmd#11]
Hi, 
I am trying to compile the AWSEM MD force field with lammps and I get a compilation error. I am following the instructions given on the git hub page. 
1) Download source code for lammps
2) cd LAMMPS_DIR/src/ 
3) make yes-molecule; make yes-rigid.       ;Required packages 
4) Copying all the .cpp and .h files from awsemmd dir to src/ 
5)make mpi 

I've tried it multiple times assuming the issue is with the user packages, However I always get an error from awsemmd files like fix_qbias.cpp, fix_backbone.cpp or fix_go-model.cpp regarding a function atan2. The specific error is : 
**error: declaration of ‘double atan2(double, double)’ has a different exception specifier
error: from previous declaration ‘double atan2(double, double) throw ()’**

I am compiling on a HPC cluster using a gcc 5.5.0 compiler.

**Comment by fonzg1** [comment]
Im having a similar issue too, however I’m using cmake to generate makefiles in a different folder. when I run make to build the code it gives me an error similar to the one you are having. but this error only happens when I add the awsemmd h and cpp files into the src folder.
 My best guess is that lammps and awsemmd might be using different versions of c++. Because up to what I have gathered from looking at the code and online docs the most recent version of lammps is using the c++11 dialect, no idk If awsemmd is using the same c++ dialect. My guess is that it’s not but that’s my best guess I think of right now. I’ll have to test this hypothesis out to see if I’m right.

**Comment by ajhaver4** [comment]
So I was able to solve this problem by using a different c++ compiler. I switched to an intel compiler from gnu and it is able to compile smoothly with the awsemmd files. I think there is a difference in the math libraries.
